name:                maze
version:             0.1.0.0
github:              "githubuser/maze"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maze#readme>

dependencies:
- base >= 4.7 && < 5
- array
- random
- mwc-random
- vector
- time
- containers
- binary
- stm
- async
- network
- text
- linear

library:
  source-dirs: src

executables:
  maze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - maze


tests:
  maze-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maze
